### ISSUE TITLE
dbld: debian stretch fails to compile

### ISSUE THREAD

**Issue by OverOrion** [syslog-ng/syslog-ng#4246]
# syslog-ng
## Version of syslog-ng
Latest master (a4c8cc4a82460daa95aab5bdffedd4f348ba382d)
## Platform

Ubuntu 20.04 LTS (Focal)

## Debug bundle

# Issue
## Failure

Running `./dbld/rules package-debian-stretch` fails with:
```
libtool: install: (cd /build/syslog-ng-3.38.1.377.ga4c8cc4/debian/build-tree; /bin/bash "/build/syslog-ng-3.38.1.377.ga4c8cc4/debian/build-tree/libtool"  --tag CC --mode=relink gcc -Wshadow -Wno-stack-protector -Wno-unused-parameter -Wno-variadic-macros -O2 -g -pthread -g -O2 -fdebug-prefix-map=/build/syslog-ng-3.38.1.377.ga4c8cc4=. -fstack-protector-strong -Wformat -Werror=format-security -avoid-version -module -no-undefined -Wl,-z,relro -o modules/rate-limit-filter/librate-limit-filter.la -rpath /usr/lib/syslog-ng/3.38 modules/rate-limit-filter/modules_rate_limit_filter_librate_limit_filter_la-rate-limit-grammar.lo modules/rate-limit-filter/modules_rate_limit_filter_librate_limit_filter_la-rate-limit-parser.lo modules/rate-limit-filter/modules_rate_limit_filter_librate_limit_filter_la-rate-limit-plugin.lo modules/rate-limit-filter/modules_rate_limit_filter_librate_limit_filter_la-rate-limit.lo ./lib/libsyslog-ng.la -inst-prefix-dir /build/syslog-ng-3.38.1.377.ga4c8cc4/debian/tmp)
libtool: relink: gcc -shared  -fPIC -DPIC  modules/rate-limit-filter/.libs/modules_rate_limit_filter_librate_limit_filter_la-rate-limit-grammar.o modules/rate-limit-filter/.libs/modules_rate_limit_filter_librate_limit_filter_la-rate-limit-parser.o modules/rate-limit-filter/.libs/modules_rate_limit_filter_librate_limit_filter_la-rate-limit-plugin.o modules/rate-limit-filter/.libs/modules_rate_limit_filter_librate_limit_filter_la-rate-limit.o   -Wl,-rpath -Wl,/usr/lib/syslog-ng -L/build/syslog-ng-3.38.1.377.ga4c8cc4/debian/tmp/usr/lib/syslog-ng -L/usr/lib/syslog-ng -lsyslog-ng  -O2 -g -pthread -g -O2 -fstack-protector-strong -Wl,-z -Wl,relro   -pthread -Wl,-soname -Wl,librate-limit-filter.so -o modules/rate-limit-filter/.libs/librate-limit-filter.so
libtool: install: /usr/bin/install -c modules/rate-limit-filter/.libs/librate-limit-filter.soT /build/syslog-ng-3.38.1.377.ga4c8cc4/debian/tmp/usr/lib/syslog-ng/3.38/librate-limit-filter.so
libtool: install: /usr/bin/install -c modules/rate-limit-filter/.libs/librate-limit-filter.lai /build/syslog-ng-3.38.1.377.ga4c8cc4/debian/tmp/usr/lib/syslog-ng/3.38/librate-limit-filter.la
libtool: warning: remember to run 'libtool --finish /usr/lib/syslog-ng/3.38'
Makefile:26075: recipe for target 'install-am' failed
make[4]: *** [install-am] Error 2
make[3]: *** [install-recursive] Error 1
Makefile:24301: recipe for target 'install-recursive' failed
make[2]: *** [install] Error 2
Makefile:26069: recipe for target 'install' failed
make[2]: Leaving directory '/build/syslog-ng-3.38.1.377.ga4c8cc4/debian/build-tree'
dh_auto_install: make -j8 install DESTDIR=/build/syslog-ng-3.38.1.377.ga4c8cc4/debian/tmp AM_UPDATE_INFO_DIR=no pkgconfigdir=/usr/lib/x86_64-linux-gnu/pkgconfig returned exit code 2
make[1]: *** [override_dh_auto_install] Error 2
debian/rules:147: recipe for target 'override_dh_auto_install' failed
make[1]: Leaving directory '/build/syslog-ng-3.38.1.377.ga4c8cc4'
debian/rules:227: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
make: *** [dbld/rules:147: package-debian-stretch] Error 2
```

I ran `git bisect` which says that 402b7dc12d9ec6fc321244929a2d811d8bf3d0a0 is most likely the culprit:
```
402b7dc12d9ec6fc321244929a2d811d8bf3d0a0 is the first bad commit
commit 402b7dc12d9ec6fc321244929a2d811d8bf3d0a0
```

**Comment by bazsi** [comment]
The issue is here:

```
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../..  -I../../lib -I../../modules -I./lib -I./modules -I../../modules/redis -I./modules/redis -Wdate-time -D_FORTIFY_SOURCE=2 -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_32 -I../../lib/eventlog/src -I./lib/eventlog/src   -D_BSD_SOURCE -D__BSD_SOURCE -D__FAVOR_BSD -DHAVE_NET_ETHERNET_H -D_DEFAULT_SOURCE -I/usr/include/dbi -I/usr/include/dbi/dbi   -D_GNU_SOURCE -D_DEFAULT_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wshadow -Wno-stack-protector -Wno-unused-parameter -Wno-variadic-macros   -D_FILE_OFFSET_BITS=64 -I/usr/include/hiredis -O2 -g -pthread -g -O2 -fdebug-prefix-map=/build/syslog-ng-3.38.1.377.ga4c8cc4=. -fstack-protector-strong -Wformat -Werror=format-security -c -o modules/redis/modules_redis_libredis_la-redis-worker.lo `test -f 'modules/redis/redis-worker.c' || echo '../../'`modules/redis/redis-worker.c
../../modules/python/python-types.c: In function ‘py_datetime_from_unix_time’:
../../modules/python/python-types.c:134:10: warning: implicit declaration of function ‘PyDateTime_FromDateAndTimeAndFold’ [-Wimplicit-function-declaration]
   return PyDateTime_FromDateAndTimeAndFold(
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../modules/python/python-types.c:134:10: warning: return makes pointer from integer without a cast [-Wint-conversion]
   return PyDateTime_FromDateAndTimeAndFold(
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            wct.wct_year + 1900, wct.wct_mon + 1, wct.wct_mday,
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            wct.wct_hour, wct.wct_min, wct.wct_sec,
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            wct.wct_usec, wct.wct_isdst > 0);
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../modules/python/python-types.c: In function ‘py_datetime_to_unix_time’:
../../modules/python/python-types.c:386:19: warning: implicit declaration of function ‘PyDateTime_DATE_GET_FOLD’ [-Wimplicit-function-declaration]
   wct.wct_isdst = PyDateTime_DATE_GET_FOLD(obj);
                   ^~~~~~~~~~~~~~~~~~~~~~~~
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../..  -I../../lib -I../../modules -I./lib -I./modules -I../../modules/redis -I./modules/redis -Wdate-time -D_FORTIFY_SOURCE=2 -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_32 -I../../lib/eventlog/src -I./lib/eventlog/src   -D_BSD_SOURCE -D__BSD_SOURCE -D__FAVOR_BSD -DHAVE_NET_ETHERNET_H -D_DEFAULT_SOURCE -I/usr/include/dbi -I/usr/include/dbi/dbi   -D_GNU_SOURCE -D_DEFAULT_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wshadow -Wno-stack-protector -Wno-unused-parameter -Wno-variadic-macros   -D_FILE_OFFSET_BITS=64 -I/usr/include/hiredis -O2 -g -pthread -g -O2 -fdebug-prefix-map=/build/syslog-ng-3.38.1.377.ga4c8cc4=. -fstack-protector-strong -Wformat -Werror=format-security -c -o modules/redis/modules_redis_libredis_la-redis-parser.lo `test -f 'modules/redis/redis-parser.c' || echo '../../'`modules/redis/redis-parser.c

```

we are depending on a new Python feature PyDateTime_FromDateAndTimeAndFold()

**Comment by bazsi** [comment]
Hmm.. this seems to start depending on Python 3.6 and stretch has Python 3.5

stretch's support period ended in 30th of June

**Comment by bazsi** [comment]
I've submitted a PR to remove support for stretch #4248

**Comment by MrAnno** [comment]
#4248 resolved this one.
