### PR TITLE
logmsg: build dump_logmsg test tool conditionally

### LINKED ISSUE #3806: compiling current git master snapshot fails on openSUSE
The DBLD CentOS 7 build worked fine, but when I tried to build on openSUSE 15.2 from the same source tgz, it failed:

```
[   73s] libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./lib -I./modules -I./lib -I./modules -I./modules/syslogformat -I./modules/syslogformat -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_28 -DGLIB_VERSION_MAX_ALLOWED=0x023C00 -I./lib/eventlog/src -I./lib/eventlog/src -DOPENSSL_LOAD_CONF -D_BSD_SOURCE -D__BSD_SOURCE -D__FAVOR_BSD -DHAVE_NET_ETHERNET_H -D_DEFAULT_SOURCE -I/usr/include/dbi -I/usr/include/dbi/dbi -isystem ./lib/ivykis/src/include -isystem ./lib/ivykis/src/include -D_GNU_SOURCE -D_DEFAULT_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wshadow -Wno-stack-protector -Wno-unused-parameter -Wno-variadic-macros -O2 -g -pthread -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -c modules/syslogformat/syslog-format.c  -fPIC -DPIC -o modules/syslogformat/.libs/libsyslogformat_la-syslog-format.o
[   73s] In file included from lib/logmsg/tests/dump_logmsg.c:23:0:
[   73s] lib/logmsg/tests/test_logmsg_serialize.c:32:10: fatal error: criterion/criterion.h: No such file or directory
[   73s]  #include <criterion/criterion.h>
[   73s]           ^~~~~~~~~~~~~~~~~~~~~~~
[   73s] compilation terminated.
[   73s] make[2]: *** [Makefile:20746: lib/logmsg/tests/dump_logmsg-dump_logmsg.o] Error 1
[   73s] make[2]: *** Waiting for unfinished jobs....
[   74s] make[1]: *** [Makefile:24490: all-recursive] Error 1
[   74s] make: *** [Makefile:10564: all] Error 2
[   74s] error: Bad exit status from /var/tmp/rpm-tmp.OcGbcz (%build)
```

I suspect, that it might be related to https://github.com/syslog-ng/syslog-ng/pull/3799 by @bazsi

### PR DESCRIPTION
**Pull request by MrAnno**
Criterion is still an optional dependency, it can only be used without
the `ENABLE_TESTING` guard in `make check` tests.

Since `noinst_PROGRAMS` builds all targets unconditionally,
an `ENABLE_TESTING` conditional has to be added manually.

Fixes #3806

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
Sorry for the mishap and thanks for fixing this up

**Review by alltilla — APPROVED** [review]
