### ISSUE TITLE
syslog-ng 3.6beta1 does not compile on FreeBSD 8.4

### ISSUE THREAD

**Issue by czanik** [syslog-ng/syslog-ng#249]
syslog-ng 3.6beta1 does not compile on FreeBSD 8.4:

  CC       lib/stats/lib_libsyslog_ng_la-stats-syslog.lo
  CC       lib/control/lib_libsyslog_ng_la-control.lo
  CC       lib/control/lib_libsyslog_ng_la-control-server.lo
lib/control/control-server.c: In function 'control_connection_io_input':
lib/control/control-server.c:138: warning: implicit declaration of function 'strchr'
lib/control/control-server.c:138: warning: incompatible implicit declaration of built-in function 'strchr'
lib/control/control-server.c:156: warning: implicit declaration of function 'strncmp'
lib/control/control-server.c:156: warning: implicit declaration of function 'strlen'
lib/control/control-server.c:156: warning: incompatible implicit declaration of built-in function 'strlen'
  CC       lib/compat/lib_libsyslog_ng_la-getutent.lo
In file included from ./lib/compat/getutent.h:33,
                 from lib/compat/getutent.c:25:
/usr/include/utmp.h:61: error: expected specifier-qualifier-list before 'int32_t'
/usr/include/utmp.h:70: error: expected specifier-qualifier-list before 'int32_t'
gmake[2]: **\* [lib/compat/lib_libsyslog_ng_la-getutent.lo] Error 1
gmake[1]: **\* [all-recursive] Error 1
gmake: **\* [all] Error 2
**\* Error code 1

Stop in /root/syslog-ng-devel.
**\* Error code 1

I was suggested to edit a few files: add `#include <string.h>` to lib/control/control-server.c and `#include <inttypes.h>` to lib/compat/getutent.h, but it did not fully solve the problem:

   CCLD     modules/afprog/libafprog.la
  CC       modules/afuser/modules_afuser_libafuser_la-afuser.lo
modules/afuser/afuser.c: In function 'afuser_dd_queue':
modules/afuser/afuser.c:134: error: 'UtmpEntry' has no member named 'ut_user'
gmake[2]: **\* [modules/afuser/modules_afuser_libafuser_la-afuser.lo] Error 1
gmake[1]: **\* [all-recursive] Error 1
gmake: **\* [all] Error 2
**\* Error code 1

Stop in /root/syslog-ng-devel.
**\* Error code 1
